---
title: "CFR Migration Tables"
author: "Nick Graetz"
output: pdf_document
geometry: margin=2cm
---
  
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Load knitr package and settings
library(knitr)
library(data.table)
library(ggplot2)
library(formatR)
library(kableExtra)
library(RColorBrewer)
options(scipen=999)
#opts_chunk$set(fig.align='center', tidy=TRUE, tidy.opts=list(blank=TRUE, width.cutoff=40), warning=FALSE,message=FALSE)
#opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
knit_hooks$set(small.mar = function(before, options, envir) {
    if (before)    par(mar=c(1,1,1,1)+.1)  # smaller margin on top and right
})
opts_chunk$set(small.mar=TRUE)
```

```{r, echo=FALSE, eval=TRUE, results='asis'}
table_1 <- readRDS('C:/Users/Nick/Documents/repos/fragile_familes/table_1.RDS')
setcolorder(table_1, c(paste0(1:6,'_white'), paste0(1:6,'_black')))
t <- kable(table_1, format = 'latex', booktabs = TRUE, caption='Summary statistics for all waves by non-Hispanic white and non-Hispanic black.', col.names = c('',c()), digits = 2, escape = FALSE) %>%
   kable_styling(latex_options = c("striped","scale_down"), full_width = T, position = "center", font_size = 8,
                 add_header_above(c(" " = 1, "White" = 6, "Black" = 6))) %>%
   add_footnote(c("* indicate parameters where p<=0.10.", "** indicate parameters where p<=0.05.", "All models include country fixed effects.")) %>%
   group_rows("", dim(main_coefs[!(cov_name %in% c('Adj. R squared', 'N')), ])[1] + 1, dim(main_coefs[!(cov_name %in% c('Adj. R squared', 'N')), ])[1] + 2) %>%
   column_spec(column = 1, width = "15em")
print(t)
```
